# Default values for Prometheus using Helm
# This file can be used as values.yaml for the Prometheus Helm chart

alertmanager:
  enabled: true

server:
  enabled: true
  service:
    type: NodePort
    nodePort: 30900
  persistentVolume:
    enabled: false

configmapReload:
  prometheus:
    enabled: true

# Example scrape config for Prometheus
serverFiles:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
